use project;
create table PRODUCT (
	pid INT,
	name VARCHAR(50),
	sid INT,
	category VARCHAR(10),
	price INT,
	stock INT,
	brand VARCHAR(50),
	rating INT,
	offer INT,
    Primary Key(pid)
);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (1, 'Ninnetta Vannar', 30, 'BOOKS', 816, 3680, 'NITROGEN', 4, 17);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (2, 'Grady Pudney', 225, 'CLOTHING', 1600, 2223, 'Tartar control plus', 2, 10);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (3, 'Claudina Blees', 92, 'BOOKS', 1708, 6742, 'VANICREAM', 2, 9);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (4, 'Maryl Althrop', 75, 'BOOKS', 224, 1643, 'Ibuprofen', 1, 19);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (5, 'Cinda Matteoli', 82, 'HOME DECOR', 1834, 5562, 'GABAPENTIN', 2, 23);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (6, 'Cindi Parsonson', 231, 'HOME DECOR', 155, 505, 'Oxycodone Hydrochloride', 5, 17);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (7, 'Friedrich Woodeson', 205, 'BOOKS', 1521, 7972, 'Ibuprofen', 1, 39);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (8, 'Svend Friskey', 187, 'BOOKS', 939, 441, 'Medicated Apricot Scrub', 1, 42);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (9, 'Lorry Philbrick', 65, 'GROCERY', 1593, 3083, 'Methylergonovine Maleate', 4, 12);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (10, 'Jillane Downage', 70, 'CLOTHING', 1524, 5654, 'flawless by Sonya aloe BB creme NUDE SPF 20 Sunscreen', 1, 46);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (11, 'Quill Pavlenko', 73, 'HOME DECOR', 1649, 2522, 'cephalexin', 1, 14);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (12, 'Deedee Caselli', 168, 'CLOTHING', 1255, 3902, 'CONDITION AND ENHANCE SYSTEM', 2, 18);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (13, 'Kacy McSkeagan', 78, 'BOOKS', 331, 3520, 'Ranitidine Hydrochloride', 4, 39);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (14, 'Arlen Byers', 1, 'CLOTHING', 312, 4528, 'Photo Plasma', 4, 41);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (15, 'Cobbie Jennins', 105, 'TECH', 573, 8569, 'Food - Fish and Shellfish, Clam', 5, 20);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (16, 'Ellerey Nancekivell', 164, 'BOOKS', 1143, 5984, 'Famotidine', 3, 27);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (17, 'Elysee Bruton', 238, 'BOOKS', 840, 9714, 'Tetracycline Hydrochloride', 1, 50);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (18, 'Orton Bandey', 197, 'CLOTHING', 1981, 2036, 'Dove Ultimate Go Fresh Burst', 3, 50);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (19, 'Marrilee Drinkhall', 156, 'CLOTHING', 360, 1127, 'Aveeno Active Naturals Essential Moisture Lip Conditioner', 1, 11);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (20, 'Leicester Puckett', 162, 'HOME DECOR', 470, 8894, 'Wart Remover Liquid', 5, 28);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (21, 'Zeb Bulbrook', 209, 'HOME DECOR', 440, 4135, 'Butalbital, Aspirin, and Caffeine', 2, 10);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (22, 'Estele Pettet', 122, 'CLOTHING', 1650, 8976, 'OXYCODONE HYDROCHLORIDE', 3, 14);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (23, 'Inglis Howles', 186, 'HOME DECOR', 1677, 7098, 'Capzasin P Arthritis Pain Relief', 5, 1);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (24, 'Tirrell Menendez', 73, 'GROCERY', 142, 8717, 'Viscum Tiliae', 1, 19);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (25, 'Alaric Mithon', 214, 'TECH', 857, 1087, 'Oto End 10', 1, 38);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (26, 'Adham Josephsen', 166, 'GROCERY', 1849, 7067, 'Stavudine', 4, 49);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (27, 'Arman Mayers', 29, 'CLOTHING', 1140, 4435, 'ARGEMONE MEXICANA', 4, 46);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (28, 'Brocky Madine', 209, 'GROCERY', 1564, 2462, 'Borrelia Babesia Remedy', 4, 15);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (29, 'Lin Addionizio', 249, 'BOOKS', 222, 8705, 'BACTOFLAM', 5, 33);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (30, 'Roana Flaherty', 66, 'GROCERY', 1308, 8825, 'Zanaflex', 4, 35);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (31, 'Shep Doughty', 205, 'CLOTHING', 166, 8102, 'Clonidine Hydrochloride', 5, 43);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (32, 'Vanya Ateridge', 132, 'GROCERY', 1002, 3515, 'Sport Mate Non-Alcohol Foaming Instant Hand Sanitizer', 4, 38);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (33, 'Gwenny Moxsom', 57, 'TECH', 600, 8949, 'CitraNatal Assure', 2, 21);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (34, 'Elyn Rowbottom', 153, 'BOOKS', 1987, 4844, 'Banana', 1, 43);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (35, 'Laina Jeannenet', 136, 'BOOKS', 1721, 7441, 'Propranolol Hydrochloride', 2, 41);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (36, 'Christoffer Elcoate', 34, 'TECH', 633, 734, 'Chestal for Children', 1, 26);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (37, 'Brina Barnhart', 230, 'CLOTHING', 1709, 4783, 'Ranitidine', 5, 42);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (38, 'Cyb Renoden', 186, 'BOOKS', 1184, 6029, 'Clearasil Ultra Rapid Action', 4, 48);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (39, 'Dolf Pleat', 120, 'HOME DECOR', 1169, 805, 'Lamotrigine', 4, 12);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (40, 'Kym Adolfson', 96, 'GROCERY', 1940, 3894, 'Health Mart Stay Awake', 4, 27);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (41, 'Tatiania Scannell', 73, 'BOOKS', 1730, 8531, 'Glyburide and Metformin', 3, 24);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (42, 'Weber Matissoff', 73, 'CLOTHING', 489, 6618, 'Losortan Potassium', 5, 42);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (43, 'Sharai Espadero', 170, 'CLOTHING', 875, 6420, 'INSTA-CHAR AQUEOUS CHERRY', 1, 12);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (44, 'Marketa Charlo', 131, 'GROCERY', 216, 1579, 'ELF Zit Zapping Conceler', 4, 38);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (45, 'Henriette Ransbury', 12, 'BOOKS', 1841, 1365, 'PAIN GOODBYE MEDICATED CREAM', 1, 43);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (46, 'Parsifal Dyer', 202, 'BOOKS', 163, 2142, 'AMOREPACIFIC', 1, 44);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (47, 'Rebbecca Christiensen', 184, 'GROCERY', 444, 1535, 'Geotrichum candidum', 1, 45);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (48, 'Lavinie Lieb', 144, 'TECH', 975, 6626, 'White Potato', 5, 39);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (49, 'Callida Fri', 215, 'BOOKS', 209, 1390, 'Humco Calamine', 3, 9);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (50, 'Hurlee Claye', 189, 'BOOKS', 258, 9569, 'L Dopa Phenolic', 3, 37);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (51, 'Florencia Espadate', 104, 'BOOKS', 1541, 1579, 'Minocycline Hydrochloride', 1, 38);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (52, 'Fina Lawly', 77, 'TECH', 1965, 1097, 'Chlorpromazine Hydrochloride', 3, 25);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (53, 'Dalenna Mant', 167, 'CLOTHING', 1508, 3325, 'BANANA BOAT', 5, 30);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (54, 'Derek Titlow', 17, 'TECH', 1019, 446, 'Tummy Aches', 2, 36);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (55, 'Oneida Woodings', 187, 'BOOKS', 886, 3613, 'Naproxen Sodium', 2, 20);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (56, 'Candi Figgess', 88, 'CLOTHING', 242, 1596, 'Pussy Willow', 5, 37);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (57, 'Ellsworth Devons', 146, 'BOOKS', 1948, 212, 'Hemorrhoid Relief', 2, 40);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (58, 'Gawen Duff', 3, 'GROCERY', 1337, 4642, 'Rosmarinus ex herba 3 Special Order', 1, 12);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (59, 'Dahlia Pavis', 177, 'GROCERY', 1476, 8252, 'Tetracycline-ABC', 5, 19);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (60, 'Jada Gutierrez', 163, 'TECH', 420, 3582, 'Nystatin', 2, 36);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (61, 'Luciana McMurtyr', 82, 'GROCERY', 890, 4318, 'Instant Hand Sanitizer Extra Enriched With Vitamin E Bead Strawberry Scent', 2, 48);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (62, 'Odelle Charge', 144, 'GROCERY', 1819, 2017, 'Soft Care Neutra Germ Fragrance Free Antibacterial', 3, 6);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (63, 'Ranee Moreside', 243, 'HOME DECOR', 1820, 9965, 'Allopurinol', 4, 31);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (64, 'Maynard Tomasicchio', 236, 'BOOKS', 969, 8670, 'Fluoxetine Hydrochloride', 2, 41);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (65, 'Emmie Erb', 121, 'CLOTHING', 559, 8467, 'Neutrogena Rapid Clear 2 in 1 Fight and Fade', 5, 7);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (66, 'Tamera Fritchly', 174, 'BOOKS', 289, 265, 'Amitriptyline Hydrochloride', 2, 12);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (67, 'Vanya Dancer', 14, 'HOME DECOR', 975, 1464, 'Natural White', 2, 41);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (68, 'Maegan Arnaudot', 221, 'CLOTHING', 8, 7795, 'FLUOROURACIL', 2, 49);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (69, 'Nicolis Greensall', 96, 'HOME DECOR', 1361, 3290, 'Good Neighbor Pharmacy Acid Reducer', 2, 27);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (70, 'Daffie Filochov', 76, 'BOOKS', 1938, 9157, 'Paroxetine', 2, 45);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (71, 'Urbain Clinch', 126, 'GROCERY', 539, 8857, 'Systane', 1, 3);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (72, 'Nikolia Markson', 91, 'GROCERY', 1359, 5476, 'AcneFree Sensitive', 1, 29);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (73, 'Roch Nevin', 125, 'BOOKS', 980, 4034, 'Arnica 30c', 3, 41);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (74, 'May Simkiss', 239, 'TECH', 537, 7094, 'PANTOPRAZOLE SODIUM', 5, 1);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (75, 'Doreen Rabbage', 192, 'HOME DECOR', 1379, 3396, 'Fluoxetine', 1, 19);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (76, 'Ania Dring', 246, 'HOME DECOR', 220, 8432, 'No7 Soft and Sheer Tinted Moisturiser Dark', 2, 28);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (77, 'Matthiew McKue', 13, 'CLOTHING', 1699, 4157, 'IBUPROFEN', 3, 6);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (78, 'Lucian Drought', 115, 'BOOKS', 1112, 5475, 'Aesculus Quercus Essence', 4, 34);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (79, 'Shamus Snailham', 215, 'BOOKS', 1079, 1792, 'Mucinex Fast-Max', 1, 5);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (80, 'Carmina Tollerton', 148, 'GROCERY', 1317, 2802, 'ZAFIRLUKAST', 5, 49);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (81, 'Joycelin Mayall', 18, 'BOOKS', 435, 3426, 'Citalopram Hydrobromide', 5, 12);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (82, 'Malina Sealey', 222, 'CLOTHING', 1726, 7420, 'DR. RECKEWEG R52 Vomisan', 1, 17);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (83, 'Maritsa Byres', 103, 'CLOTHING', 804, 8292, 'Buspirone Hydrochloride', 2, 17);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (84, 'Kiersten Durnill', 244, 'GROCERY', 1607, 6709, 'Naproxen Sodium', 1, 31);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (85, 'Ira Trobey', 141, 'CLOTHING', 38, 2489, 'equaline omeprazole', 4, 1);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (86, 'Cirstoforo Roskeilly', 199, 'TECH', 1947, 5681, 'Olanzapine', 1, 3);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (87, 'Korry Stenner', 163, 'CLOTHING', 869, 4805, 'Ciprofloxacin', 3, 39);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (88, 'Leigh Maun', 249, 'BOOKS', 1417, 2477, 'Heparin Lock Flush', 2, 10);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (89, 'Ynez Marquess', 1, 'HOME DECOR', 168, 815, 'Amlodipine besylate/atorvastatin calcium', 5, 4);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (90, 'Melinda Sante', 96, 'CLOTHING', 159, 8631, 'Quality Choice Iodides Tincture', 2, 2);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (91, 'Nananne Aikenhead', 120, 'BOOKS', 1313, 9663, 'ControlRx', 1, 21);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (92, 'Alan Easey', 200, 'HOME DECOR', 1085, 8079, 'Purminerals 4 in 1 Makeup SPF 15 Light', 1, 10);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (93, 'Gipsy Setchell', 154, 'HOME DECOR', 806, 5301, 'CRYSTAL MIRACLE MULTI', 2, 30);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (94, 'Chariot Dunk', 216, 'TECH', 1373, 8778, 'Risperidone', 1, 30);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (95, 'Kirby Broadway', 25, 'CLOTHING', 96, 3805, 'ULORIC', 5, 18);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (96, 'Luisa Herety', 187, 'HOME DECOR', 1820, 2163, 'DIOVAN HCT', 4, 10);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (97, 'Collette Spuner', 49, 'CLOTHING', 1824, 7451, 'NUCYNTA', 4, 27);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (98, 'Annissa Mallinder', 185, 'GROCERY', 430, 5140, 'COTTON FIBER', 5, 37);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (99, 'Graham Legging', 110, 'GROCERY', 1547, 9626, 'Velvet Grass', 4, 49);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (100, 'Candy Gallety', 181, 'CLOTHING', 881, 9243, 'NATURAL HONEY HERB COUGH SUPPRESSANT THROAT DROPS', 2, 29);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (101, 'Stern Leveret', 207, 'CLOTHING', 1294, 3779, 'Ritalin', 4, 34);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (102, 'Lucien Cluatt', 132, 'CLOTHING', 523, 6746, 'Topiclear Paris Beauty', 4, 11);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (103, 'Holly Mournian', 155, 'GROCERY', 1143, 101, 'safeHands', 1, 5);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (104, 'Camala Brayley', 201, 'TECH', 1852, 1653, 'Metronidazole', 5, 7);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (105, 'Weider Gosnell', 132, 'CLOTHING', 43, 3807, 'ropinirole', 3, 30);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (106, 'Jerrie Eagell', 54, 'BOOKS', 1539, 8369, 'Opana', 2, 28);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (107, 'Yetta Gaisford', 130, 'HOME DECOR', 380, 2618, 'Tartar control plus', 4, 13);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (108, 'Adolpho Forcade', 199, 'CLOTHING', 1532, 5187, 'Neutrogena MoistureShine SPF20', 4, 1);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (109, 'Raymund Cockroft', 210, 'BOOKS', 177, 2791, 'Earwax Removal Aid', 3, 25);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (110, 'Madelle Huncote', 214, 'GROCERY', 28, 5736, 'Quality Choice Multi-Symptom, Non-Drowsy DayTime Cold and Flu', 5, 10);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (111, 'Jordon Meeks', 43, 'TECH', 1276, 5787, 'ropinirole', 4, 15);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (112, 'Hirsch Iles', 51, 'HOME DECOR', 1539, 9768, 'CARBON DIOXIDE', 3, 47);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (113, 'Welsh Petrus', 140, 'BOOKS', 293, 8234, 'Prograf', 3, 22);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (114, 'Fenelia Avis', 106, 'GROCERY', 329, 9870, 'Nifedipine', 1, 18);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (115, 'Ethelred Orlton', 196, 'BOOKS', 476, 4327, 'LBEL REPLENISHING FOUNDATION SPF 14', 5, 29);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (116, 'Alphonse Lummus', 33, 'GROCERY', 48, 7923, 'L OCCITANE AU BRESIL - JENIPAPO Protecting Body Jelly Milk SPF 20 Broad Spectrum', 2, 2);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (117, 'Raphaela Angeli', 135, 'HOME DECOR', 1314, 7269, 'Otis Clapp Valihist', 4, 27);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (118, 'Cherida Genike', 112, 'HOME DECOR', 488, 3776, 'X Viate', 1, 26);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (119, 'Cletis Jahnel', 96, 'TECH', 1933, 7282, 'Neutrogena SkinClearing', 5, 5);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (120, 'Tabb Stockell', 145, 'BOOKS', 1085, 9347, 'Dial Complete Antibacterial Foaming Hand Wash with Lotion', 3, 45);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (121, 'Bobbie O''Rudden', 119, 'GROCERY', 1195, 4466, 'Oxycodone Hydrochloride', 1, 20);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (122, 'Corette Seabon', 30, 'TECH', 1137, 5761, 'XtraCare Creamy Petroleum Jelly', 2, 48);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (123, 'Ellette Lacroux', 227, 'HOME DECOR', 1997, 8083, 'Novolin70/30', 5, 23);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (124, 'Heywood Pittoli', 213, 'GROCERY', 614, 6815, 'Verapamil Hydrochloride', 2, 1);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (125, 'Dougie Edgson', 18, 'TECH', 88, 4808, 'pain and fever', 2, 34);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (126, 'June Tour', 43, 'CLOTHING', 709, 3592, 'Crest Pro-Health', 1, 7);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (127, 'Mae Vassar', 67, 'BOOKS', 4, 4626, 'Sotalol Hydrochloride', 4, 5);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (128, 'Fey Glowacz', 15, 'HOME DECOR', 666, 5475, 'Dicyclomine', 1, 12);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (129, 'Cyrus Scoffins', 102, 'CLOTHING', 960, 4636, 'ASPERGILLUS NIGER VAR NIGER', 2, 7);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (130, 'Agace Housby', 141, 'TECH', 1031, 3175, 'Noxzema', 2, 6);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (131, 'Alvin Trebbett', 182, 'TECH', 780, 4704, 'LISINOPRIL', 2, 24);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (132, 'Angeli Lapworth', 58, 'CLOTHING', 1357, 9319, 'Kiehls Since 1851 Activated Sun Protector For Body Broad Spectrum SPF 50 Sunscreen', 2, 43);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (133, 'Shawn Duinkerk', 202, 'BOOKS', 399, 2440, 'Gelato APF', 1, 2);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (134, 'Emanuel Mycock', 210, 'GROCERY', 1505, 6202, 'Pain Relief PM', 1, 9);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (135, 'Teri Herche', 118, 'HOME DECOR', 99, 4824, 'Up and Up allergy and congestion relief', 3, 32);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (136, 'Ilise Greenacre', 50, 'HOME DECOR', 844, 6954, 'LBEL COULEUR LUXE AMPLIFIER XP', 3, 25);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (137, 'Abbott Huby', 1, 'BOOKS', 21, 9887, 'ropinirole', 2, 39);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (138, 'Shellie McDaid', 146, 'TECH', 1034, 8930, 'Multi-Symptom Cold and Cough Daytime Nighttime', 1, 39);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (139, 'Diann Dmitrovic', 173, 'BOOKS', 1257, 163, 'nicotine', 2, 15);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (140, 'Suzette McNeachtain', 60, 'GROCERY', 294, 1212, 'ARC FIRST AID Contains 303 PIECES', 4, 37);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (141, 'Northrop Worsom', 99, 'GROCERY', 360, 9390, 'Aspirin EC', 3, 27);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (142, 'Cass Lamke', 154, 'TECH', 709, 2100, 'Naproxen', 4, 10);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (143, 'Adan Pattinson', 152, 'CLOTHING', 416, 5549, 'CARBIDOPA AND LEVODOPA', 5, 33);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (144, 'Beale Kleint', 20, 'BOOKS', 1273, 2368, 'Gabapentin', 5, 14);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (145, 'Riki Windrus', 129, 'TECH', 213, 2776, 'Amlodipine Besylate', 1, 22);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (146, 'Deirdre Ickowics', 242, 'BOOKS', 700, 5428, 'Dr.eslee Sun Protection', 1, 47);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (147, 'Avrom Reitenbach', 107, 'CLOTHING', 981, 5963, 'Glyburide', 3, 4);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (148, 'Moreen Cassley', 190, 'GROCERY', 1114, 2060, 'Levetiracetam', 5, 6);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (149, 'Valaree Simpole', 103, 'TECH', 1467, 4027, 'NITROGEN', 5, 45);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (150, 'Jordan Elsworth', 135, 'BOOKS', 1661, 9898, 'Gongjinhyang Qi and Jin Eye', 5, 47);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (151, 'Ric Mattheis', 93, 'BOOKS', 555, 7668, 'DIPYRIDAMOLE', 1, 19);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (152, 'Delmore Lethabridge', 249, 'TECH', 562, 3716, 'Acure Mineral Protection Sunscreen Broad Spectrum SPF 30', 2, 29);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (153, 'Rahel Gosz', 188, 'BOOKS', 525, 1020, 'Cloderm', 2, 1);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (154, 'Quintin Jertz', 156, 'HOME DECOR', 1274, 9586, 'ADVAIR', 3, 9);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (155, 'Denise Talby', 94, 'HOME DECOR', 793, 7619, 'ORIGINAL POWER WHITENING AND LINELESS AMPOULE', 2, 47);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (156, 'Arabelle Favel', 23, 'HOME DECOR', 952, 2542, 'Zermat Xtreme Roll-On Antiperspirant Deodorant', 2, 50);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (157, 'Leopold Maceur', 240, 'HOME DECOR', 1355, 8234, 'Equaline Mucus ER', 4, 48);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (158, 'Pebrook Hutchings', 66, 'BOOKS', 416, 9231, 'Walgreens', 4, 24);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (159, 'Martie Smorthit', 167, 'GROCERY', 534, 6709, 'Neomycin, Polymyxin B Sulfates and Hydrocortisone', 5, 50);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (160, 'Shellysheldon Lindner', 87, 'TECH', 95, 8145, 'Oil-Free Foaming Acne Wash Facial Cleanser', 1, 29);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (161, 'Rich Over', 143, 'TECH', 1558, 697, 'Bloating Complex', 4, 48);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (162, 'Dominique Jillard', 194, 'GROCERY', 15, 2578, 'Ferrum Quartz', 2, 44);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (163, 'Maje Nortunen', 227, 'HOME DECOR', 1037, 919, 'Metformin Hydrochloride', 1, 47);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (164, 'Stella Du Hamel', 204, 'GROCERY', 1267, 4097, 'PHOSPHORUS', 5, 3);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (165, 'Holt Rickhuss', 174, 'BOOKS', 1513, 2936, 'Gehwol Nail Protection Pen', 3, 31);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (166, 'Hilda Ambrosoni', 238, 'GROCERY', 38, 9796, 'Childrens Pain Relief', 2, 19);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (167, 'Wallace Rudham', 198, 'TECH', 1650, 4276, 'OBAGI-C RX SYSTEM NORMAL-DRY', 3, 24);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (168, 'Birch Marrow', 152, 'HOME DECOR', 1509, 307, 'METHADOSE', 1, 1);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (169, 'Gerrard Defond', 150, 'CLOTHING', 683, 9446, 'Ropinirole Hydrochloride', 3, 3);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (170, 'Jolyn De Giovanni', 9, 'CLOTHING', 1574, 948, 'sunmark miconazole 3', 2, 40);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (171, 'Chris Bulgen', 98, 'BOOKS', 1418, 5762, 'FACIAL CLEANSER', 2, 31);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (172, 'Elisha Conisbee', 121, 'TECH', 1080, 5946, 'Acella Hydrocortisone Acetate - Pramoxine Singles', 1, 46);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (173, 'Ive Bartel', 119, 'GROCERY', 968, 4015, 'Appetite Control', 4, 9);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (174, 'Rodi Geroldini', 149, 'HOME DECOR', 1862, 19, 'Ketorolac Tromethamine', 1, 32);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (175, 'Anatola Powell', 225, 'GROCERY', 528, 7232, 'Endoxcin', 1, 5);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (176, 'Flo Sanper', 109, 'BOOKS', 1685, 1324, 'Hydralazine Hydrochloride', 2, 10);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (177, 'Gertrude Twidell', 250, 'CLOTHING', 1009, 2825, 'Redness reliever', 2, 17);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (178, 'Costa Branchet', 19, 'GROCERY', 654, 9624, 'Oxygen', 1, 5);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (179, 'Genia Zelner', 45, 'HOME DECOR', 1584, 7833, 'Tamsulosin Hydrochloride', 1, 17);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (180, 'Kalli Pestridge', 244, 'GROCERY', 990, 6921, 'flormar Soft Touch Foundation Sunscreen Broad Spectrum SPF 20 ST03 Natural Pink', 5, 40);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (181, 'Andres Dawney', 32, 'BOOKS', 1241, 7117, 'Omeprazole', 2, 18);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (182, 'Ajay Dun', 74, 'CLOTHING', 232, 9337, 'ANTIBACTERIAL FOAMING', 1, 38);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (183, 'Linn Menel', 40, 'GROCERY', 1572, 9285, 'PerioChip', 4, 45);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (184, 'Thibaut Lumsdale', 17, 'BOOKS', 1590, 3211, 'Dextrose And Sodium Chloride', 5, 35);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (185, 'Elwin Truce', 136, 'BOOKS', 1993, 1957, 'IASO White Science EX', 2, 40);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (186, 'Gaynor Pescott', 24, 'BOOKS', 400, 762, 'Burrobrush Pollen', 4, 26);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (187, 'Althea Yukhnini', 210, 'TECH', 1030, 9164, 'DR. RECKEWEG R49 Rhinopulsan', 1, 5);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (188, 'Smitty Pigdon', 110, 'GROCERY', 473, 3251, 'SHEER FOCUS', 5, 26);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (189, 'Tova Capper', 136, 'BOOKS', 51, 3605, 'Murine Tears for Dry Eyes', 1, 40);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (190, 'Loise Pedron', 218, 'TECH', 1714, 4233, 'nifedipine', 4, 35);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (191, 'Marketa Karmel', 59, 'TECH', 95, 7317, 'Cultivated Rye', 5, 15);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (192, 'Marcos Bevar', 81, 'CLOTHING', 504, 3204, 'SIMVASTATIN', 2, 28);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (193, 'Darsey Graser', 98, 'GROCERY', 1347, 7877, 'ropinirole', 2, 18);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (194, 'Katusha Guiu', 59, 'HOME DECOR', 677, 9618, 'Captopril', 3, 28);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (195, 'Tito Phippard', 14, 'CLOTHING', 1968, 7241, 'Lisinopril', 3, 40);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (196, 'Matty Emilien', 170, 'CLOTHING', 1968, 762, 'Adderall', 2, 7);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (197, 'Maurizia Athowe', 216, 'CLOTHING', 1605, 5744, 'Alert', 4, 26);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (198, 'Jonah Bulcroft', 168, 'BOOKS', 742, 6954, 'CYTRA', 2, 5);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (199, 'Clarance Saunper', 74, 'HOME DECOR', 1552, 5040, 'Reglan', 4, 11);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (200, 'Mikael Bisterfeld', 208, 'CLOTHING', 721, 7520, 'SPRYCEL', 1, 14);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (201, 'Zonda Fransinelli', 189, 'GROCERY', 1970, 5215, 'Levothyroxine Sodium', 2, 40);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (202, 'Gabriella Taw', 14, 'TECH', 762, 6848, 'Somatuline Depot', 4, 28);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (203, 'Perl MacIlraith', 138, 'HOME DECOR', 145, 5759, 'lansoprazole', 4, 33);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (204, 'Lucilia Gilstin', 186, 'CLOTHING', 1305, 6047, 'CENTER-AL - PLANTAGO LANCEOLATA POLLEN', 1, 47);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (205, 'Al Cicutto', 7, 'GROCERY', 675, 7074, 'SEROQUEL', 3, 3);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (206, 'Ashlin Pattie', 232, 'CLOTHING', 672, 2069, 'Heparin Sodium', 2, 36);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (207, 'Lisabeth Liepmann', 3, 'BOOKS', 1504, 4046, 'ibuprofen', 1, 18);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (208, 'Flss Lovegrove', 215, 'GROCERY', 1425, 6282, 'Kool Heat Pain Therapy', 2, 39);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (209, 'Van But', 144, 'CLOTHING', 720, 9548, 'Nifedipine', 4, 33);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (210, 'Ariela Assel', 89, 'HOME DECOR', 1132, 95, 'hydrocortisone acetate pramoxine HCl', 5, 1);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (211, 'Alvan Baudone', 25, 'HOME DECOR', 1895, 4166, 'Prednisone', 4, 11);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (212, 'Hughie Fiddy', 220, 'CLOTHING', 505, 470, 'Acyclovir', 2, 15);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (213, 'Mead Strafen', 144, 'CLOTHING', 1003, 1145, 'Montelukast Sodium', 1, 13);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (214, 'Pierrette Vell', 223, 'HOME DECOR', 1924, 932, 'Nabumetone', 4, 29);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (215, 'Lanae Beggini', 215, 'HOME DECOR', 90, 5092, 'Thai Herbal Balm Lemon Grass', 3, 3);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (216, 'Zachariah Crome', 149, 'GROCERY', 1132, 288, 'Ketorolac Tromethamine', 3, 8);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (217, 'Lewie Glassup', 12, 'GROCERY', 1502, 2047, 'SMOKE-X', 3, 26);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (218, 'Ogdan Fetherston', 136, 'GROCERY', 1150, 4242, 'DOK', 5, 39);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (219, 'Essa Pistol', 36, 'CLOTHING', 208, 3851, 'ESIKA HYDRACOLOR 2 IN 1 HIGHLY MOISTURIZING AND COLORING SPF 25', 4, 14);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (220, 'Naomi Stammler', 247, 'TECH', 552, 3485, 'Bruises-Muscle Soreness', 5, 27);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (221, 'Angy Tidmarsh', 145, 'TECH', 170, 2397, 'Slim', 3, 16);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (222, 'Boniface Kiddie', 228, 'BOOKS', 803, 1489, 'Nitrofurantoin Monohydrate/ Macrocrystalline', 5, 37);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (223, 'Brion Moxstead', 250, 'CLOTHING', 1636, 6474, 'Strawberry', 3, 11);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (224, 'Correna Dennistoun', 111, 'GROCERY', 1398, 3647, 'OXYGEN', 5, 31);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (225, 'Shalna Force', 91, 'TECH', 1376, 5231, 'FACTIVE', 1, 41);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (226, 'Pen Spellissy', 60, 'HOME DECOR', 156, 6521, 'Redtop Grass, Standardized', 4, 28);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (227, 'Romona Dunnan', 239, 'GROCERY', 1584, 9315, 'Kids Crest', 3, 44);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (228, 'Mariele Scorah', 178, 'CLOTHING', 1577, 2417, 'LBEL HYDRATESS', 5, 3);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (229, 'Bryn Hyndes', 242, 'TECH', 232, 3345, 'Frosted cranberry anti-bacterial SCENTED HAND SANITIZER', 3, 37);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (230, 'Elliot Rogerson', 244, 'HOME DECOR', 1593, 2178, 'Correct and Perfect Spot Treatment', 3, 31);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (231, 'Burgess Skudder', 55, 'CLOTHING', 1366, 8432, 'ALPRAZOLAM EXTENDED-RELEASE', 1, 24);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (232, 'Shirley Cratere', 179, 'BOOKS', 1811, 7180, 'HYDROCODONE BITARTRATE AND ACETAMINOPHEN', 4, 32);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (233, 'Shae Haslum', 247, 'GROCERY', 343, 2354, 'Atovaquone and Proguanil Hydrochloride', 1, 32);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (234, 'Putnam Pacher', 207, 'CLOTHING', 450, 1498, 'Gynobalance', 1, 48);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (235, 'Elberta Antonikov', 151, 'CLOTHING', 333, 718, 'CitraNatal DHA', 5, 5);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (236, 'Hadria Chappel', 83, 'TECH', 227, 2108, 'topcare antacid calcium', 1, 33);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (237, 'Lonnie Tofpik', 37, 'CLOTHING', 478, 1961, 'Boscia Self-Defense Vital Antioxidant Moisture Broad Spectrum SPF 30', 2, 18);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (238, 'Gerrie Hicklingbottom', 94, 'CLOTHING', 1043, 302, 'COUMADIN', 3, 27);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (239, 'Nicolette Davidovitz', 219, 'HOME DECOR', 691, 2130, 'Brewers Yeast', 1, 26);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (240, 'Natasha Francais', 211, 'TECH', 1535, 6055, 'KIDNEY DRAINAGE', 5, 7);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (241, 'Bernarr Newport', 99, 'GROCERY', 1275, 1704, 'Gillette Clinical', 5, 47);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (242, 'Kristin Brigshaw', 29, 'GROCERY', 1144, 807, 'Diphenhydramine HCL', 1, 34);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (243, 'Bailey Farmery', 212, 'CLOTHING', 640, 2967, 'Suphedrine PE', 1, 23);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (244, 'Brigg Dunkley', 100, 'BOOKS', 1886, 9015, 'Viscum Salicis', 3, 49);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (245, 'Bailie Upchurch', 197, 'CLOTHING', 1231, 1747, 'Venlafaxine Hydrochloride', 2, 13);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (246, 'Nickie Cholonin', 184, 'TECH', 525, 935, 'SENSAI SILK 10 SECONDS AWAKENING ESSENCE', 5, 27);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (247, 'Joy Clashe', 154, 'BOOKS', 1156, 5818, 'Lemon and Basil Antibacterial Foaming Hand Wash', 2, 29);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (248, 'Pippo Geator', 41, 'HOME DECOR', 1131, 3102, 'Kleen Instant Hand Sanitizer with Moisturizers', 3, 23);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (249, 'Dar Colthurst', 97, 'BOOKS', 1384, 1909, 'Cold - Sinus', 4, 47);
insert into PRODUCT (pid, name, sid, category, price, stock, brand, rating, offer) values (250, 'Wayne Barnardo', 140, 'BOOKS', 1725, 9381, 'Motofen', 5, 37);
