use project;
create table QUERIES (
	cid INT,
	message TEXT,
	status VARCHAR(50),
	timestamp VARCHAR(50)
);
insert into QUERIES (cid, message, status, timestamp) values (1, 'nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et', true, '1:43 PM');
insert into QUERIES (cid, message, status, timestamp) values (2, 'pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue', true, '6:12 AM');
insert into QUERIES (cid, message, status, timestamp) values (3, 'tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec', false, '11:50 PM');
insert into QUERIES (cid, message, status, timestamp) values (4, 'ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam', true, '7:04 PM');
insert into QUERIES (cid, message, status, timestamp) values (5, 'accumsan tellus nisi eu orci mauris lacinia sapien quis libero', false, '5:12 AM');
insert into QUERIES (cid, message, status, timestamp) values (6, 'purus phasellus in felis donec semper sapien a libero nam', false, '3:27 PM');
insert into QUERIES (cid, message, status, timestamp) values (7, 'erat fermentum justo nec condimentum neque sapien placerat ante nulla', false, '5:49 PM');
insert into QUERIES (cid, message, status, timestamp) values (8, 'maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus sapien ut', true, '8:59 PM');
insert into QUERIES (cid, message, status, timestamp) values (9, 'in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus', false, '10:59 PM');
insert into QUERIES (cid, message, status, timestamp) values (10, 'augue a suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit', true, '8:47 PM');
insert into QUERIES (cid, message, status, timestamp) values (11, 'integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor', false, '8:06 PM');
insert into QUERIES (cid, message, status, timestamp) values (12, 'posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit', false, '6:26 PM');
insert into QUERIES (cid, message, status, timestamp) values (13, 'sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla', false, '8:29 AM');
insert into QUERIES (cid, message, status, timestamp) values (14, 'vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in', false, '4:00 PM');
insert into QUERIES (cid, message, status, timestamp) values (15, 'nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla', true, '1:48 AM');
insert into QUERIES (cid, message, status, timestamp) values (16, 'morbi quis tortor id nulla ultrices aliquet maecenas leo odio', true, '5:08 PM');
insert into QUERIES (cid, message, status, timestamp) values (17, 'porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor', false, '9:00 AM');
insert into QUERIES (cid, message, status, timestamp) values (18, 'ut nulla sed accumsan felis ut at dolor quis odio', false, '2:26 AM');
insert into QUERIES (cid, message, status, timestamp) values (19, 'est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed', true, '3:46 PM');
insert into QUERIES (cid, message, status, timestamp) values (20, 'commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt', false, '11:31 PM');
insert into QUERIES (cid, message, status, timestamp) values (21, 'viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec', false, '7:12 AM');
insert into QUERIES (cid, message, status, timestamp) values (22, 'at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae', true, '5:03 AM');
insert into QUERIES (cid, message, status, timestamp) values (23, 'nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo', false, '8:19 AM');
insert into QUERIES (cid, message, status, timestamp) values (24, 'nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu', true, '6:36 PM');
insert into QUERIES (cid, message, status, timestamp) values (25, 'sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit donec diam neque vestibulum', true, '2:02 PM');
insert into QUERIES (cid, message, status, timestamp) values (26, 'ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis', true, '11:57 AM');
insert into QUERIES (cid, message, status, timestamp) values (27, 'semper sapien a libero nam dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut', true, '11:29 AM');
insert into QUERIES (cid, message, status, timestamp) values (28, 'curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis', true, '11:36 AM');
insert into QUERIES (cid, message, status, timestamp) values (29, 'ornare consequat lectus in est risus auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc', false, '10:25 AM');
insert into QUERIES (cid, message, status, timestamp) values (30, 'tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit', true, '10:02 PM');
insert into QUERIES (cid, message, status, timestamp) values (31, 'id consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio consequat varius', true, '2:45 AM');
insert into QUERIES (cid, message, status, timestamp) values (32, 'luctus cum sociis natoque penatibus et magnis dis parturient montes', false, '9:06 PM');
insert into QUERIES (cid, message, status, timestamp) values (33, 'nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium', false, '10:02 AM');
insert into QUERIES (cid, message, status, timestamp) values (34, 'morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam', true, '9:52 AM');
insert into QUERIES (cid, message, status, timestamp) values (35, 'sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae', false, '8:03 AM');
insert into QUERIES (cid, message, status, timestamp) values (36, 'nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem', false, '6:16 AM');
insert into QUERIES (cid, message, status, timestamp) values (37, 'quis turpis sed ante vivamus tortor duis mattis egestas metus', true, '5:03 PM');
insert into QUERIES (cid, message, status, timestamp) values (38, 'elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy', false, '7:40 AM');
insert into QUERIES (cid, message, status, timestamp) values (39, 'in lacus curabitur at ipsum ac tellus semper interdum mauris', true, '10:09 PM');
insert into QUERIES (cid, message, status, timestamp) values (40, 'est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed', true, '2:07 PM');
insert into QUERIES (cid, message, status, timestamp) values (41, 'aliquet at feugiat non pretium quis lectus suspendisse potenti in', false, '3:00 AM');
insert into QUERIES (cid, message, status, timestamp) values (42, 'vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo', true, '4:44 PM');
insert into QUERIES (cid, message, status, timestamp) values (43, 'nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum', true, '5:25 AM');
insert into QUERIES (cid, message, status, timestamp) values (44, 'congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a', false, '6:08 AM');
insert into QUERIES (cid, message, status, timestamp) values (45, 'mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in', false, '11:13 AM');
insert into QUERIES (cid, message, status, timestamp) values (46, 'consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices', false, '1:51 PM');
insert into QUERIES (cid, message, status, timestamp) values (47, 'turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis', false, '9:26 PM');
insert into QUERIES (cid, message, status, timestamp) values (48, 'pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices', false, '1:49 AM');
insert into QUERIES (cid, message, status, timestamp) values (49, 'lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend quam a odio in hac', true, '12:55 AM');
insert into QUERIES (cid, message, status, timestamp) values (50, 'tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in', true, '7:04 PM');
insert into QUERIES (cid, message, status, timestamp) values (51, 'condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et', false, '6:59 AM');
insert into QUERIES (cid, message, status, timestamp) values (52, 'quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia', false, '2:46 PM');
insert into QUERIES (cid, message, status, timestamp) values (53, 'ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae mauris', false, '9:26 AM');
insert into QUERIES (cid, message, status, timestamp) values (54, 'tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl', true, '2:18 PM');
insert into QUERIES (cid, message, status, timestamp) values (55, 'nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula', false, '5:13 AM');
insert into QUERIES (cid, message, status, timestamp) values (56, 'metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci', true, '9:44 AM');
insert into QUERIES (cid, message, status, timestamp) values (57, 'curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in leo', true, '6:40 PM');
insert into QUERIES (cid, message, status, timestamp) values (58, 'id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat', false, '6:18 AM');
insert into QUERIES (cid, message, status, timestamp) values (59, 'a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices', true, '6:53 AM');
insert into QUERIES (cid, message, status, timestamp) values (60, 'ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia', true, '1:08 AM');
insert into QUERIES (cid, message, status, timestamp) values (61, 'vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis', false, '6:43 PM');
insert into QUERIES (cid, message, status, timestamp) values (62, 'eros viverra eget congue eget semper rutrum nulla nunc purus', true, '2:15 PM');
insert into QUERIES (cid, message, status, timestamp) values (63, 'sagittis dui vel nisl duis ac nibh fusce lacus purus', false, '10:07 AM');
insert into QUERIES (cid, message, status, timestamp) values (64, 'ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas', true, '8:50 PM');
insert into QUERIES (cid, message, status, timestamp) values (65, 'quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus', true, '11:54 AM');
insert into QUERIES (cid, message, status, timestamp) values (66, 'velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat', false, '3:53 AM');
insert into QUERIES (cid, message, status, timestamp) values (67, 'eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus', false, '2:14 AM');
insert into QUERIES (cid, message, status, timestamp) values (68, 'erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam', true, '7:35 PM');
insert into QUERIES (cid, message, status, timestamp) values (69, 'aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst', true, '4:10 PM');
insert into QUERIES (cid, message, status, timestamp) values (70, 'molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec', false, '2:17 PM');
insert into QUERIES (cid, message, status, timestamp) values (71, 'curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum', false, '9:50 AM');
insert into QUERIES (cid, message, status, timestamp) values (72, 'orci luctus et ultrices posuere cubilia curae mauris viverra diam', false, '9:18 PM');
insert into QUERIES (cid, message, status, timestamp) values (73, 'euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at', false, '7:48 PM');
insert into QUERIES (cid, message, status, timestamp) values (74, 'quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus', false, '3:49 AM');
insert into QUERIES (cid, message, status, timestamp) values (75, 'sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam', true, '1:17 PM');
insert into QUERIES (cid, message, status, timestamp) values (76, 'est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin', false, '3:43 PM');
insert into QUERIES (cid, message, status, timestamp) values (77, 'quisque arcu libero rutrum ac lobortis vel dapibus at diam nam tristique tortor', false, '3:41 AM');
insert into QUERIES (cid, message, status, timestamp) values (78, 'suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non', true, '9:59 PM');
insert into QUERIES (cid, message, status, timestamp) values (79, 'sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim', false, '5:59 PM');
insert into QUERIES (cid, message, status, timestamp) values (80, 'nunc purus phasellus in felis donec semper sapien a libero nam dui proin', false, '3:06 AM');
insert into QUERIES (cid, message, status, timestamp) values (81, 'dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus', true, '2:53 PM');
insert into QUERIES (cid, message, status, timestamp) values (82, 'cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem', false, '6:17 PM');
insert into QUERIES (cid, message, status, timestamp) values (83, 'urna pretium nisl ut volutpat sapien arcu sed augue aliquam', false, '10:46 AM');
insert into QUERIES (cid, message, status, timestamp) values (84, 'nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel', false, '4:34 PM');
insert into QUERIES (cid, message, status, timestamp) values (85, 'quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus', true, '3:07 AM');
insert into QUERIES (cid, message, status, timestamp) values (86, 'orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices', true, '6:22 AM');
insert into QUERIES (cid, message, status, timestamp) values (87, 'orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui', true, '10:03 PM');
insert into QUERIES (cid, message, status, timestamp) values (88, 'fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc', true, '7:38 AM');
insert into QUERIES (cid, message, status, timestamp) values (89, 'nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum', false, '7:08 AM');
insert into QUERIES (cid, message, status, timestamp) values (90, 'volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus', true, '6:45 AM');
insert into QUERIES (cid, message, status, timestamp) values (91, 'vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes', false, '4:14 AM');
insert into QUERIES (cid, message, status, timestamp) values (92, 'habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum', false, '9:50 AM');
insert into QUERIES (cid, message, status, timestamp) values (93, 'in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla', false, '10:53 PM');
insert into QUERIES (cid, message, status, timestamp) values (94, 'vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec', false, '8:42 AM');
insert into QUERIES (cid, message, status, timestamp) values (95, 'odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi', false, '10:06 PM');
insert into QUERIES (cid, message, status, timestamp) values (96, 'nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra', false, '11:58 PM');
insert into QUERIES (cid, message, status, timestamp) values (97, 'diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna', true, '2:10 AM');
insert into QUERIES (cid, message, status, timestamp) values (98, 'quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero', true, '2:16 PM');
insert into QUERIES (cid, message, status, timestamp) values (99, 'leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu', false, '2:34 PM');
insert into QUERIES (cid, message, status, timestamp) values (100, 'in felis donec semper sapien a libero nam dui proin leo odio porttitor id consequat in consequat ut nulla', false, '11:51 PM');
insert into QUERIES (cid, message, status, timestamp) values (101, 'metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in', true, '4:09 PM');
insert into QUERIES (cid, message, status, timestamp) values (102, 'nunc viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus', false, '5:33 AM');
insert into QUERIES (cid, message, status, timestamp) values (103, 'habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida', false, '8:46 PM');
insert into QUERIES (cid, message, status, timestamp) values (104, 'nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere', true, '1:59 PM');
insert into QUERIES (cid, message, status, timestamp) values (105, 'rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at', true, '8:07 PM');
insert into QUERIES (cid, message, status, timestamp) values (106, 'vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit', true, '5:34 AM');
insert into QUERIES (cid, message, status, timestamp) values (107, 'ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed', true, '9:37 AM');
insert into QUERIES (cid, message, status, timestamp) values (108, 'augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero', false, '8:38 AM');
insert into QUERIES (cid, message, status, timestamp) values (109, 'pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et', true, '5:37 PM');
insert into QUERIES (cid, message, status, timestamp) values (110, 'suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas', false, '3:39 AM');
insert into QUERIES (cid, message, status, timestamp) values (111, 'est phasellus sit amet erat nulla tempus vivamus in felis eu', true, '5:18 AM');
insert into QUERIES (cid, message, status, timestamp) values (112, 'parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum', true, '2:42 AM');
insert into QUERIES (cid, message, status, timestamp) values (113, 'in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate', false, '2:37 AM');
insert into QUERIES (cid, message, status, timestamp) values (114, 'tellus semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis vel dapibus at diam nam', true, '10:57 AM');
insert into QUERIES (cid, message, status, timestamp) values (115, 'massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris', true, '5:12 AM');
insert into QUERIES (cid, message, status, timestamp) values (116, 'fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat', true, '4:30 AM');
insert into QUERIES (cid, message, status, timestamp) values (117, 'velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget', true, '5:38 AM');
insert into QUERIES (cid, message, status, timestamp) values (118, 'massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut', true, '1:00 PM');
insert into QUERIES (cid, message, status, timestamp) values (119, 'pede venenatis non sodales sed tincidunt eu felis fusce posuere', true, '3:03 AM');
insert into QUERIES (cid, message, status, timestamp) values (120, 'fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis', false, '9:44 PM');
insert into QUERIES (cid, message, status, timestamp) values (121, 'at turpis a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices', true, '9:22 AM');
insert into QUERIES (cid, message, status, timestamp) values (122, 'eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit', false, '8:47 PM');
insert into QUERIES (cid, message, status, timestamp) values (123, 'neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor', false, '4:45 AM');
insert into QUERIES (cid, message, status, timestamp) values (124, 'sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non', false, '12:28 PM');
insert into QUERIES (cid, message, status, timestamp) values (125, 'mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit', true, '6:00 AM');
insert into QUERIES (cid, message, status, timestamp) values (126, 'orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras', false, '8:41 PM');
insert into QUERIES (cid, message, status, timestamp) values (127, 'pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit amet nunc', false, '8:29 PM');
insert into QUERIES (cid, message, status, timestamp) values (128, 'integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio', false, '1:07 AM');
insert into QUERIES (cid, message, status, timestamp) values (129, 'est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus', false, '6:32 AM');
insert into QUERIES (cid, message, status, timestamp) values (130, 'iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales', true, '8:47 PM');
insert into QUERIES (cid, message, status, timestamp) values (131, 'sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae', false, '8:36 AM');
insert into QUERIES (cid, message, status, timestamp) values (132, 'penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum', false, '2:28 PM');
insert into QUERIES (cid, message, status, timestamp) values (133, 'lectus pellentesque at nulla suspendisse potenti cras in purus eu', true, '2:51 AM');
insert into QUERIES (cid, message, status, timestamp) values (134, 'praesent lectus vestibulum quam sapien varius ut blandit non interdum in ante vestibulum ante ipsum primis in faucibus orci', false, '5:01 PM');
insert into QUERIES (cid, message, status, timestamp) values (135, 'vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend quam', false, '3:40 PM');
insert into QUERIES (cid, message, status, timestamp) values (136, 'duis aliquam convallis nunc proin at turpis a pede posuere nonummy', true, '3:02 AM');
insert into QUERIES (cid, message, status, timestamp) values (137, 'purus aliquet at feugiat non pretium quis lectus suspendisse potenti', false, '10:40 PM');
insert into QUERIES (cid, message, status, timestamp) values (138, 'enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum', true, '9:47 PM');
insert into QUERIES (cid, message, status, timestamp) values (139, 'nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse platea', true, '11:09 AM');
insert into QUERIES (cid, message, status, timestamp) values (140, 'morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim', false, '2:25 AM');
insert into QUERIES (cid, message, status, timestamp) values (141, 'sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta', true, '8:49 PM');
insert into QUERIES (cid, message, status, timestamp) values (142, 'lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu', false, '1:51 AM');
insert into QUERIES (cid, message, status, timestamp) values (143, 'primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor', true, '1:25 PM');
insert into QUERIES (cid, message, status, timestamp) values (144, 'at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis', true, '5:18 PM');
insert into QUERIES (cid, message, status, timestamp) values (145, 'fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet', true, '12:29 PM');
insert into QUERIES (cid, message, status, timestamp) values (146, 'posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed', false, '3:02 AM');
insert into QUERIES (cid, message, status, timestamp) values (147, 'quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque', false, '5:44 PM');
insert into QUERIES (cid, message, status, timestamp) values (148, 'dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio consequat', false, '4:58 PM');
insert into QUERIES (cid, message, status, timestamp) values (149, 'non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum', false, '12:18 AM');
insert into QUERIES (cid, message, status, timestamp) values (150, 'volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar', true, '6:36 AM');
insert into QUERIES (cid, message, status, timestamp) values (151, 'enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in', true, '12:21 AM');
insert into QUERIES (cid, message, status, timestamp) values (152, 'nulla nunc purus phasellus in felis donec semper sapien a libero nam dui proin leo odio porttitor', false, '7:14 PM');
insert into QUERIES (cid, message, status, timestamp) values (153, 'lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla', true, '4:03 AM');
insert into QUERIES (cid, message, status, timestamp) values (154, 'nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget', true, '11:23 AM');
insert into QUERIES (cid, message, status, timestamp) values (155, 'id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus', false, '9:32 AM');
insert into QUERIES (cid, message, status, timestamp) values (156, 'cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis', true, '3:05 PM');
insert into QUERIES (cid, message, status, timestamp) values (157, 'ut massa volutpat convallis morbi odio odio elementum eu interdum eu', true, '3:37 PM');
insert into QUERIES (cid, message, status, timestamp) values (158, 'posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel', false, '6:59 AM');
insert into QUERIES (cid, message, status, timestamp) values (159, 'suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus nulla', false, '1:18 AM');
insert into QUERIES (cid, message, status, timestamp) values (160, 'integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis', true, '11:50 PM');
insert into QUERIES (cid, message, status, timestamp) values (161, 'cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor', false, '11:29 AM');
insert into QUERIES (cid, message, status, timestamp) values (162, 'nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce', true, '12:05 AM');
insert into QUERIES (cid, message, status, timestamp) values (163, 'in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec', false, '2:12 AM');
insert into QUERIES (cid, message, status, timestamp) values (164, 'ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit', true, '4:52 AM');
insert into QUERIES (cid, message, status, timestamp) values (165, 'orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer', true, '9:17 AM');
insert into QUERIES (cid, message, status, timestamp) values (166, 'sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus', false, '1:17 AM');
insert into QUERIES (cid, message, status, timestamp) values (167, 'pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus', false, '12:03 AM');
insert into QUERIES (cid, message, status, timestamp) values (168, 'lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet', true, '2:14 AM');
insert into QUERIES (cid, message, status, timestamp) values (169, 'cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam', true, '12:04 PM');
insert into QUERIES (cid, message, status, timestamp) values (170, 'justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus', true, '7:40 PM');
insert into QUERIES (cid, message, status, timestamp) values (171, 'vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra', false, '3:02 PM');
insert into QUERIES (cid, message, status, timestamp) values (172, 'sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum', false, '11:59 AM');
insert into QUERIES (cid, message, status, timestamp) values (173, 'tempus vivamus in felis eu sapien cursus vestibulum proin eu mi', false, '8:31 AM');
insert into QUERIES (cid, message, status, timestamp) values (174, 'nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus', true, '10:29 AM');
insert into QUERIES (cid, message, status, timestamp) values (175, 'accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in', false, '3:46 AM');
insert into QUERIES (cid, message, status, timestamp) values (176, 'nulla nunc purus phasellus in felis donec semper sapien a libero nam dui proin leo odio porttitor id consequat in', true, '9:41 AM');
insert into QUERIES (cid, message, status, timestamp) values (177, 'sed accumsan felis ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices', true, '7:26 PM');
insert into QUERIES (cid, message, status, timestamp) values (178, 'volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in', true, '1:04 PM');
insert into QUERIES (cid, message, status, timestamp) values (179, 'neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis', false, '11:03 PM');
insert into QUERIES (cid, message, status, timestamp) values (180, 'orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a', true, '11:20 PM');
insert into QUERIES (cid, message, status, timestamp) values (181, 'mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus', true, '1:13 PM');
insert into QUERIES (cid, message, status, timestamp) values (182, 'sagittis dui vel nisl duis ac nibh fusce lacus purus', false, '8:33 AM');
insert into QUERIES (cid, message, status, timestamp) values (183, 'est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est', true, '3:48 PM');
insert into QUERIES (cid, message, status, timestamp) values (184, 'cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel', false, '11:44 AM');
insert into QUERIES (cid, message, status, timestamp) values (185, 'dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet', false, '4:21 PM');
insert into QUERIES (cid, message, status, timestamp) values (186, 'vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat', true, '11:34 PM');
insert into QUERIES (cid, message, status, timestamp) values (187, 'orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in', true, '7:40 PM');
insert into QUERIES (cid, message, status, timestamp) values (188, 'vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit', false, '3:07 PM');
insert into QUERIES (cid, message, status, timestamp) values (189, 'quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum', true, '1:18 AM');
insert into QUERIES (cid, message, status, timestamp) values (190, 'donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla', true, '11:26 AM');
insert into QUERIES (cid, message, status, timestamp) values (191, 'enim blandit mi in porttitor pede justo eu massa donec dapibus duis at velit eu est congue', true, '12:50 PM');
insert into QUERIES (cid, message, status, timestamp) values (192, 'vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient', false, '5:28 PM');
insert into QUERIES (cid, message, status, timestamp) values (193, 'ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis vel dapibus', false, '9:06 AM');
insert into QUERIES (cid, message, status, timestamp) values (194, 'urna pretium nisl ut volutpat sapien arcu sed augue aliquam', true, '4:31 AM');
insert into QUERIES (cid, message, status, timestamp) values (195, 'donec semper sapien a libero nam dui proin leo odio', true, '8:22 AM');
insert into QUERIES (cid, message, status, timestamp) values (196, 'volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie', true, '10:24 PM');
insert into QUERIES (cid, message, status, timestamp) values (197, 'elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec', true, '4:53 PM');
insert into QUERIES (cid, message, status, timestamp) values (198, 'sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut', false, '6:03 AM');
insert into QUERIES (cid, message, status, timestamp) values (199, 'maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin', true, '2:06 PM');
insert into QUERIES (cid, message, status, timestamp) values (200, 'turpis eget elit sodales scelerisque mauris sit amet eros suspendisse', true, '12:19 AM');
insert into QUERIES (cid, message, status, timestamp) values (201, 'sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum', true, '1:31 AM');
insert into QUERIES (cid, message, status, timestamp) values (202, 'hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla', true, '6:13 AM');
insert into QUERIES (cid, message, status, timestamp) values (203, 'in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec', true, '11:44 AM');
insert into QUERIES (cid, message, status, timestamp) values (204, 'turpis a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante', false, '7:29 AM');
insert into QUERIES (cid, message, status, timestamp) values (205, 'ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue', false, '1:57 PM');
insert into QUERIES (cid, message, status, timestamp) values (206, 'vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae', false, '5:13 AM');
insert into QUERIES (cid, message, status, timestamp) values (207, 'sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices', true, '1:09 PM');
insert into QUERIES (cid, message, status, timestamp) values (208, 'est risus auctor sed tristique in tempus sit amet sem fusce consequat', true, '8:39 PM');
insert into QUERIES (cid, message, status, timestamp) values (209, 'sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus', true, '5:55 PM');
insert into QUERIES (cid, message, status, timestamp) values (210, 'molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum', true, '11:35 AM');
insert into QUERIES (cid, message, status, timestamp) values (211, 'malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer', true, '1:51 AM');
insert into QUERIES (cid, message, status, timestamp) values (212, 'hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat', true, '9:36 AM');
insert into QUERIES (cid, message, status, timestamp) values (213, 'pretium iaculis diam erat fermentum justo nec condimentum neque sapien', false, '12:03 AM');
insert into QUERIES (cid, message, status, timestamp) values (214, 'curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel', true, '1:52 PM');
insert into QUERIES (cid, message, status, timestamp) values (215, 'eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a', false, '4:41 AM');
insert into QUERIES (cid, message, status, timestamp) values (216, 'ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id', false, '6:22 PM');
insert into QUERIES (cid, message, status, timestamp) values (217, 'sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget', false, '8:34 AM');
insert into QUERIES (cid, message, status, timestamp) values (218, 'justo in hac habitasse platea dictumst etiam faucibus cursus urna ut', false, '7:12 AM');
insert into QUERIES (cid, message, status, timestamp) values (219, 'dapibus nulla suscipit ligula in lacus curabitur at ipsum ac', false, '3:39 AM');
insert into QUERIES (cid, message, status, timestamp) values (220, 'tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque', true, '11:10 PM');
insert into QUERIES (cid, message, status, timestamp) values (221, 'turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at', false, '1:57 AM');
insert into QUERIES (cid, message, status, timestamp) values (222, 'consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu', false, '11:31 PM');
insert into QUERIES (cid, message, status, timestamp) values (223, 'eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque at', true, '7:36 PM');
insert into QUERIES (cid, message, status, timestamp) values (224, 'at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget', false, '12:33 PM');
insert into QUERIES (cid, message, status, timestamp) values (225, 'blandit non interdum in ante vestibulum ante ipsum primis in faucibus orci luctus et', true, '1:03 AM');
insert into QUERIES (cid, message, status, timestamp) values (226, 'eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor', false, '10:31 AM');
insert into QUERIES (cid, message, status, timestamp) values (227, 'suspendisse ornare consequat lectus in est risus auctor sed tristique', false, '10:01 AM');
insert into QUERIES (cid, message, status, timestamp) values (228, 'sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque', false, '10:48 PM');
insert into QUERIES (cid, message, status, timestamp) values (229, 'sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at', true, '8:55 AM');
insert into QUERIES (cid, message, status, timestamp) values (230, 'aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut', true, '2:15 AM');
insert into QUERIES (cid, message, status, timestamp) values (231, 'at vulputate vitae nisl aenean lectus pellentesque eget nunc donec', false, '7:55 AM');
insert into QUERIES (cid, message, status, timestamp) values (232, 'integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed', true, '8:50 PM');
insert into QUERIES (cid, message, status, timestamp) values (233, 'ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam', true, '5:33 AM');
insert into QUERIES (cid, message, status, timestamp) values (234, 'diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque', true, '6:32 PM');
insert into QUERIES (cid, message, status, timestamp) values (235, 'in porttitor pede justo eu massa donec dapibus duis at velit eu est congue elementum in', true, '4:32 AM');
insert into QUERIES (cid, message, status, timestamp) values (236, 'diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue', false, '12:16 AM');
insert into QUERIES (cid, message, status, timestamp) values (237, 'fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus', false, '3:05 PM');
insert into QUERIES (cid, message, status, timestamp) values (238, 'orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris', false, '10:34 AM');
insert into QUERIES (cid, message, status, timestamp) values (239, 'pretium quis lectus suspendisse potenti in eleifend quam a odio in', true, '7:46 PM');
insert into QUERIES (cid, message, status, timestamp) values (240, 'mauris morbi non lectus aliquam sit amet diam in magna', false, '1:53 PM');
insert into QUERIES (cid, message, status, timestamp) values (241, 'curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac', true, '8:34 PM');
insert into QUERIES (cid, message, status, timestamp) values (242, 'rutrum nulla nunc purus phasellus in felis donec semper sapien a', true, '7:51 AM');
insert into QUERIES (cid, message, status, timestamp) values (243, 'eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla', true, '6:37 AM');
insert into QUERIES (cid, message, status, timestamp) values (244, 'erat volutpat in congue etiam justo etiam pretium iaculis justo', true, '9:10 AM');
insert into QUERIES (cid, message, status, timestamp) values (245, 'vel nisl duis ac nibh fusce lacus purus aliquet at feugiat', true, '7:06 PM');
insert into QUERIES (cid, message, status, timestamp) values (246, 'sed tristique in tempus sit amet sem fusce consequat nulla nisl', true, '1:29 AM');
insert into QUERIES (cid, message, status, timestamp) values (247, 'nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti', false, '12:12 PM');
insert into QUERIES (cid, message, status, timestamp) values (248, 'id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque', false, '4:03 PM');
insert into QUERIES (cid, message, status, timestamp) values (249, 'posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac', false, '1:05 AM');
insert into QUERIES (cid, message, status, timestamp) values (250, 'felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed', true, '5:35 AM');
