use project;
create table WAREHOUSE (
	WID INT,
	CITY VARCHAR(50),
	STATE VARCHAR(50),
	PINCODE INT,
	EID int
);
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (1, 'Sandvika', 'Akershus', 43946, '13');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (2, 'Leduc', 'Alberta', 44384, '56');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (3, 'Bordeaux', 'Aquitaine', 26943, '185');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (4, 'Grande Cache', 'Alberta', 38051, '50');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (5, 'Rennes', 'Bretagne', 42630, '3');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (6, 'Sherwood Park', 'Alberta', 19678, '102');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (7, 'Libourne', 'Aquitaine', 14090, '104');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (8, 'Bordeaux', 'Aquitaine', 26040, '76');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (9, 'Noyal-sur-Vilaine', 'Bretagne', 49584, '122');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (10, 'Two Hills', 'Alberta', 32592, '136');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (11, 'Pessac', 'Aquitaine', 45953, '226');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (12, 'Blaye', 'Aquitaine', 30981, '168');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (13, 'Cestas', 'Aquitaine', 22477, '175');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (14, 'Noyal-sur-Vilaine', 'Bretagne', 33674, '124');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (15, 'Saint-Malo', 'Bretagne', 16706, '40');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (16, 'High River', 'Alberta', 28709, '117');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (17, 'Libourne', 'Aquitaine', 38587, '55');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (18, 'Mérignac', 'Aquitaine', 42399, '9');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (19, 'Rennes', 'Bretagne', 43713, '211');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (20, 'Bordeaux', 'Aquitaine', 42332, '26');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (21, 'Brest', 'Bretagne', 46661, '82');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (22, 'Fort McMurray', 'Alberta', 26277, '106');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (23, 'Brest', 'Bretagne', 23888, '89');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (24, 'Gibbons', 'Alberta', 37727, '137');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (25, 'Bordeaux', 'Aquitaine', 24076, '94');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (26, 'Pau', 'Aquitaine', 43841, '134');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (27, 'Spirit River', 'Alberta', 44998, '62');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (28, 'Rennes', 'Bretagne', 32425, '83');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (29, 'Airdrie', 'Alberta', 25616, '24');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (30, 'Marmande', 'Aquitaine', 44986, '36');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (31, 'Hanna', 'Alberta', 42339, '28');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (32, 'Banff', 'Alberta', 33908, '199');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (33, 'Cochrane', 'Alberta', 30807, '65');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (34, 'Millet', 'Alberta', 32359, '11');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (35, 'Pessac', 'Aquitaine', 31814, '178');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (36, 'Manning', 'Alberta', 12803, '68');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (37, 'Fox Creek', 'Alberta', 31226, '155');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (38, 'Bordeaux', 'Aquitaine', 37875, '233');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (39, 'Pau', 'Aquitaine', 45878, '116');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (40, 'Agen', 'Aquitaine', 48882, '96');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (41, 'High River', 'Alberta', 31034, '109');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (42, 'Barrhead', 'Alberta', 12786, '241');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (43, 'Asker', 'Akershus', 34902, '16');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (44, 'Saint-Brieuc', 'Bretagne', 38870, '51');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (45, 'Pau', 'Aquitaine', 12155, '121');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (46, 'Trélissac', 'Aquitaine', 14334, '71');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (47, 'Bordeaux', 'Aquitaine', 22095, '197');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (48, 'Fort Macleod', 'Alberta', 16646, '84');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (49, 'Pau', 'Aquitaine', 35172, '206');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (50, 'Lescar', 'Aquitaine', 49715, '150');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (51, 'Lescar', 'Aquitaine', 15593, '202');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (52, 'Bonnyville', 'Alberta', 22546, '130');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (53, 'Douarnenez', 'Bretagne', 33892, '236');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (54, 'Two Hills', 'Alberta', 49997, '246');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (55, 'Irricana', 'Alberta', 49678, '172');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (56, 'Spirit River', 'Alberta', 10661, '143');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (57, 'Logroño', 'La Rioja', 46504, '140');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (58, 'Floirac', 'Aquitaine', 16677, '66');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (59, 'Quimper', 'Bretagne', 22752, '153');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (60, 'Agen', 'Aquitaine', 43879, '176');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (61, 'Bordeaux', 'Aquitaine', 46919, '17');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (62, 'Rennes', 'Bretagne', 34851, '209');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (63, 'Calmar', 'Alberta', 24874, '231');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (64, 'Cesson-Sévigné', 'Bretagne', 16783, '29');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (65, 'Rennes', 'Bretagne', 30075, '229');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (66, 'Cesson-Sévigné', 'Bretagne', 12690, '30');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (67, 'Lacombe', 'Alberta', 42933, '37');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (68, 'Millet', 'Alberta', 39330, '95');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (69, 'Sundre', 'Alberta', 34028, '227');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (70, 'Logroño', 'La Rioja', 49878, '161');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (71, 'Rennes', 'Bretagne', 11231, '234');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (72, 'Rennes', 'Bretagne', 35740, '18');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (73, 'Brest', 'Bretagne', 25194, '6');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (74, 'Sherwood Park', 'Alberta', 34930, '25');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (75, 'Crossfield', 'Alberta', 43994, '151');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (76, 'Trélissac', 'Aquitaine', 24707, '162');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (77, 'Locminé', 'Bretagne', 26877, '75');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (78, 'Bordeaux', 'Aquitaine', 22021, '186');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (79, 'Hendaye', 'Aquitaine', 13296, '157');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (80, 'Peace River', 'Alberta', 27422, '114');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (81, 'Bayonne', 'Aquitaine', 14921, '63');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (82, 'Ploemeur', 'Bretagne', 16303, '86');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (83, 'Périgueux', 'Aquitaine', 20487, '78');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (84, 'Logroño', 'La Rioja', 23991, '44');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (85, 'Cochrane', 'Alberta', 42808, '4');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (86, 'Brest', 'Bretagne', 25771, '21');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (87, 'Brest', 'Bretagne', 18171, '163');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (88, 'Nanton', 'Alberta', 41109, '181');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (89, 'Grande Prairie', 'Alberta', 12675, '100');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (90, 'Airdrie', 'Alberta', 21693, '126');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (91, 'Banff', 'Alberta', 46780, '41');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (92, 'Rocky Mountain House', 'Alberta', 16137, '61');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (93, 'Olds', 'Alberta', 41080, '224');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (94, 'Rennes', 'Bretagne', 18924, '142');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (95, 'Bayonne', 'Aquitaine', 33308, '223');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (96, 'Quimper', 'Bretagne', 43305, '240');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (97, 'Rennes', 'Bretagne', 45750, '46');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (98, 'Rennes', 'Bretagne', 46287, '208');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (99, 'Olds', 'Alberta', 26706, '80');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (100, 'Rennes', 'Bretagne', 48240, '193');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (101, 'Douarnenez', 'Bretagne', 37303, '132');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (102, 'Calgary', 'Alberta', 47867, '188');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (103, 'Guingamp', 'Bretagne', 31390, '15');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (104, 'Saint-Brieuc', 'Bretagne', 14616, '238');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (105, 'High Prairie', 'Alberta', 32559, '160');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (106, 'Plérin', 'Bretagne', 38942, '138');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (107, 'Hendaye', 'Aquitaine', 29819, '32');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (108, 'Peace River', 'Alberta', 18750, '235');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (109, 'Fort Macleod', 'Alberta', 49117, '148');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (110, 'Rennes', 'Bretagne', 48852, '204');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (111, 'Bergerac', 'Aquitaine', 34314, '98');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (112, 'Agen', 'Aquitaine', 39366, '232');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (113, 'Jasper Park Lodge', 'Alberta', 30372, '45');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (114, 'Quimper', 'Bretagne', 48242, '20');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (115, 'Crossfield', 'Alberta', 26448, '115');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (116, 'Vannes', 'Bretagne', 24238, '64');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (117, 'Vulcan', 'Alberta', 14825, '218');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (118, 'Pau', 'Aquitaine', 43961, '79');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (119, 'Cochrane', 'Alberta', 14568, '69');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (120, 'Bordeaux', 'Aquitaine', 13987, '144');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (121, 'Strathmore', 'Alberta', 18992, '27');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (122, 'Lorient', 'Bretagne', 44768, '189');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (123, 'Bordeaux', 'Aquitaine', 49783, '154');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (124, 'Olds', 'Alberta', 15090, '133');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (125, 'Vulcan', 'Alberta', 39688, '158');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (126, 'Bordeaux', 'Aquitaine', 41632, '167');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (127, 'Cestas', 'Aquitaine', 40098, '248');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (128, 'Asker', 'Akershus', 29788, '97');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (129, 'Beaverlodge', 'Alberta', 45962, '179');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (130, 'Irricana', 'Alberta', 44465, '7');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (131, 'Lorient', 'Bretagne', 17636, '72');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (132, 'Bayonne', 'Aquitaine', 33294, '107');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (133, 'Leduc', 'Alberta', 12105, '225');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (134, 'Stony Plain', 'Alberta', 47805, '103');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (135, 'Claresholm', 'Alberta', 38632, '221');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (136, 'Calgary', 'Alberta', 36447, '123');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (137, 'Bergerac', 'Aquitaine', 16424, '213');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (138, 'Spirit River', 'Alberta', 19994, '93');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (139, 'Agen', 'Aquitaine', 34583, '147');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (140, 'Bayonne', 'Aquitaine', 21189, '173');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (141, 'Bordeaux', 'Aquitaine', 35565, '219');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (142, 'Chantepie', 'Bretagne', 14459, '217');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (143, 'Fort Macleod', 'Alberta', 10550, '237');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (144, 'Pau', 'Aquitaine', 39696, '149');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (145, 'Raymond', 'Alberta', 18194, '145');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (146, 'Pau', 'Aquitaine', 10935, '222');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (147, 'Rennes', 'Bretagne', 11276, '35');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (148, 'Medicine Hat', 'Alberta', 12827, '125');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (149, 'Barrhead', 'Alberta', 15827, '164');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (150, 'Grimshaw', 'Alberta', 15254, '5');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (151, 'Rennes', 'Bretagne', 25555, '212');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (152, 'Brest', 'Bretagne', 19027, '171');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (153, 'Brest', 'Bretagne', 30174, '118');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (154, 'Rocky Mountain House', 'Alberta', 15656, '70');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (155, 'Brest', 'Bretagne', 18775, '200');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (156, 'Quimperlé', 'Bretagne', 45536, '57');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (157, 'Mérignac', 'Aquitaine', 35840, '244');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (158, 'Périgueux', 'Aquitaine', 29656, '39');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (159, 'Logroño', 'La Rioja', 30517, '38');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (160, 'Brest', 'Bretagne', 42953, '239');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (161, 'Bergerac', 'Aquitaine', 26290, '194');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (162, 'Smoky Lake', 'Alberta', 35209, '159');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (163, 'Logroño', 'La Rioja', 21890, '81');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (164, 'Redon', 'Bretagne', 16904, '34');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (165, 'Saint-Malo', 'Bretagne', 33376, '146');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (166, 'Saint-Brieuc', 'Bretagne', 21099, '249');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (167, 'Saint-Jouan-des-Guérets', 'Bretagne', 34936, '105');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (168, 'Pontivy', 'Bretagne', 22982, '228');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (169, 'Barrhead', 'Alberta', 11963, '110');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (170, 'High Prairie', 'Alberta', 16679, '180');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (171, 'Devon', 'Alberta', 10897, '177');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (172, 'Mérignac', 'Aquitaine', 43353, '108');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (173, 'Rennes', 'Bretagne', 37058, '169');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (174, 'Medicine Hat', 'Alberta', 27768, '203');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (175, 'Fox Creek', 'Alberta', 17954, '77');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (176, 'Fox Creek', 'Alberta', 10415, '119');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (177, 'Pessac', 'Aquitaine', 45901, '43');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (178, 'Jasper Park Lodge', 'Alberta', 27170, '92');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (179, 'Rocky Mountain House', 'Alberta', 10926, '195');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (180, 'Vannes', 'Bretagne', 25270, '129');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (181, 'Rocky Mountain House', 'Alberta', 45452, '42');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (182, 'Vulcan', 'Alberta', 26688, '139');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (183, 'Bordeaux', 'Aquitaine', 29683, '33');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (184, 'Millet', 'Alberta', 32185, '131');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (185, 'Lescar', 'Aquitaine', 33472, '174');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (186, 'Sandvika', 'Akershus', 24591, '112');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (187, 'Vegreville', 'Alberta', 25389, '58');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (188, 'Bonnyville', 'Alberta', 20518, '210');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (189, 'Bordeaux', 'Aquitaine', 37709, '215');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (190, 'Devon', 'Alberta', 18432, '85');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (191, 'Devon', 'Alberta', 37362, '22');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (192, 'Smoky Lake', 'Alberta', 23730, '53');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (193, 'Dinan', 'Bretagne', 49085, '230');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (194, 'Saint-Jean-de-Luz', 'Aquitaine', 18755, '220');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (195, 'Agen', 'Aquitaine', 25543, '214');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (196, 'Rennes', 'Bretagne', 30468, '192');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (197, 'Floirac', 'Aquitaine', 10393, '14');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (198, 'Brest', 'Bretagne', 27938, '47');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (199, 'Vegreville', 'Alberta', 45382, '242');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (200, 'Two Hills', 'Alberta', 22954, '183');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (201, 'Calmar', 'Alberta', 46034, '170');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (202, 'Saint-Brieuc', 'Bretagne', 34735, '201');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (203, 'Périgueux', 'Aquitaine', 13857, '31');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (204, 'Quimper', 'Bretagne', 33845, '73');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (205, 'High River', 'Alberta', 42754, '128');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (206, 'Airdrie', 'Alberta', 46442, '109');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (207, 'Claresholm', 'Alberta', 10649, '12');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (208, 'Vannes', 'Bretagne', 12712, '202');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (209, 'Canmore', 'Alberta', 28502, '113');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (210, 'Dinan', 'Bretagne', 19611, '140');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (211, 'Saint-Jean-de-Luz', 'Aquitaine', 42503, '85');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (212, 'Taber', 'Alberta', 25094, '230');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (213, 'Camrose', 'Alberta', 47186, '16');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (214, 'Pau', 'Aquitaine', 41363, '250');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (215, 'Rennes', 'Bretagne', 38471, '105');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (216, 'Lethbridge', 'Alberta', 18204, '108');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (217, 'Redon', 'Bretagne', 45655, '101');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (218, 'Calgary', 'Alberta', 39761, '186');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (219, 'Coaldale', 'Alberta', 17572, '129');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (220, 'Spirit River', 'Alberta', 22395, '61');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (221, 'Bordeaux', 'Aquitaine', 49911, '1');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (222, 'Spirit River', 'Alberta', 48127, '58');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (223, 'Saint-Brieuc', 'Bretagne', 48661, '171');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (224, 'Pincher Creek', 'Alberta', 30210, '56');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (225, 'Sundre', 'Alberta', 28117, '94');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (226, 'Billère', 'Aquitaine', 26826, '135');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (227, 'Agen', 'Aquitaine', 40574, '35');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (228, 'Cestas', 'Aquitaine', 14917, '165');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (229, 'Raymond', 'Alberta', 31388, '195');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (230, 'Douarnenez', 'Bretagne', 38173, '95');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (231, 'Saint-Grégoire', 'Bretagne', 39622, '127');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (232, 'Pau', 'Aquitaine', 13077, '249');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (233, 'Agen', 'Aquitaine', 27967, '50');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (234, 'Bègles', 'Aquitaine', 14412, '211');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (235, 'Roscoff', 'Bretagne', 42461, '100');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (236, 'Hanna', 'Alberta', 36428, '102');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (237, 'Gibbons', 'Alberta', 49977, '37');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (238, 'Camrose', 'Alberta', 13263, '39');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (239, 'Agen', 'Aquitaine', 15270, '112');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (240, 'Saint-Brieuc', 'Bretagne', 44563, '71');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (241, 'Auray', 'Bretagne', 21115, '192');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (242, 'Pessac', 'Aquitaine', 47427, '70');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (243, 'Auray', 'Bretagne', 38014, '106');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (244, 'Smoky Lake', 'Alberta', 15374, '151');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (245, 'Quimper', 'Bretagne', 23331, '60');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (246, 'Drayton Valley', 'Alberta', 35895, '241');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (247, 'Asker', 'Akershus', 20845, '31');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (248, 'Logroño', 'La Rioja', 24150, '121');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (249, 'Asker', 'Akershus', 11301, '116');
insert into WAREHOUSE (WID, CITY, STATE, PINCODE, EID) values (250, 'Coaldale', 'Alberta', 15754, '143');
